arb-dir: lib/l10n
template-arb-file: app_en.arb
output-localization-file: app_localizations.dart
output-class: AppLocalizations
# The generated class lives in lib/l10n next to the ARB files.
nullable-getter: false
